Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "docker"
  
  config.vm.network "private_network", ip:"10.10.10.20"
  
  config.vm.provision "shell", path:"docker.sh"
end
