version: '3.1'

services: 
  nomads_web:
    image: nomads_web_img
    hostname: www
    domainname: nomads.fr.to
    build: 
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 80:80

